In [1]:
import pandas as pd

In [2]:
iris=pd.read_json('iris.json')
iris

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [3]:
import mysql.connector

In [4]:
data=mysql.connector.connect(host='localhost',user='root',password='',database='world')

InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 No connection could be made because the target machine actively refused it)

In [ ]:
df=pd.read_sql_query('select * from city',data)

C:\Users\hp\AppData\Local\Temp\ipykernel_19848\947231853.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query('select * from city',data)

In [ ]:
df.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [ ]:
pd.read_sql_query('select * from city where Population>1000000',data)

C:\Users\hp\AppData\Local\Temp\ipykernel_19848\1069571975.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from city where Population>1000000',data)

       ID          Name CountryCode          District  Population
0       1         Kabul         AFG             Kabol     1780000
1      35         Alger         DZA             Alger     2168000
2      56        Luanda         AGO            Luanda     2022000
3      69  Buenos Aires         ARG  Distrito Federal     2982146
4      70    La Matanza         ARG      Buenos Aires     1266461
..    ...           ...         ...               ...         ...
232  3798       Phoenix         USA           Arizona     1321045
233  3799     San Diego         USA        California     1223400
234  3800        Dallas         USA             Texas     1188580
235  3801   San Antonio         USA             Texas     1144646
236  4068        Harare         ZWE            Harare     1410000

[237 rows x 5 columns]

In [ ]:
IND=pd.read_sql_query('select * from city where CountryCode like "IND"',data)
IND

C:\Users\hp\AppData\Local\Temp\ipykernel_19848\2350340827.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  IND=pd.read_sql_query('select * from city where CountryCode like "IND"',data)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [ ]:
pd.read_sql_query('select * from country where IndepYear>1945',data)

C:\Users\hp\AppData\Local\Temp\ipykernel_19848\2972694692.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from country where IndepYear>1945',data)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AGO,Angola,Africa,Central Africa,1246700.0,1975,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56,AO
1,ARE,United Arab Emirates,Asia,Middle East,83600.0,1971,2441000,74.1,37966.0,36846.0,Al-Imarat al-´Arabiya al-Muttahida,Emirate Federation,Zayid bin Sultan al-Nahayan,65,AE
2,ARM,Armenia,Asia,Middle East,29800.0,1991,3520000,66.4,1813.0,1627.0,Hajastan,Republic,Robert Kotšarjan,126,AM
3,ATG,Antigua and Barbuda,North America,Caribbean,442.0,1981,68000,70.5,612.0,584.0,Antigua and Barbuda,Constitutional Monarchy,Elisabeth II,63,AG
4,AZE,Azerbaijan,Asia,Middle East,86600.0,1991,7734000,62.9,4127.0,4100.0,Azärbaycan,Federal Republic,Heydär Äliyev,144,AZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,VCT,Saint Vincent and the Grenadines,North America,Caribbean,388.0,1979,114000,72.3,285.0,NaN,Saint Vincent and the Grenadines,Constitutional Monarchy,Elisabeth II,3066,VC
115,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537,VU
116,WSM,Samoa,Oceania,Polynesia,2831.0,1962,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169,WS
117,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162,ZM
118,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068,ZW

In [ ]:
import requests

In [ ]:
requests.get('https://reqres.in/api/users?api_key=***&page=1')